Feature/2
ftp-andrei/GrupoUnown pull request #17
Opened 2022-11-23 15:40 UTC by DanielAlonsoDAW

2022-11-23 15:47 UTC, TRdeXtremiana approved these changes

2022-11-23 15:54 UTC, Kuroval requested changes
Pon etiquetas semánticas

2022-11-23 15:54 UTC, alexpmAW requested changes
Use semantic tags, nav, main,header

2022-11-23 16:04 UTC, alexpmAW approved these changes

2022-11-23 16:04 UTC, Kuroval approved these changes

2022-11-23 16:24 UTC, ftp-andrei approved these changes
Va

2022-11-24 16:08 UTC, Kuroval requested changes
Pon el video encima del texto, dentro del main o fuera entre el main y el nav eso como quieras.

2022-11-24 22:23 UTC, Kuroval approved these changes

2022-11-27 11:23 UTC, merged