Feature/15
ftp-andrei/GrupoUnown pull request #18
Opened 2022-11-23 15:42 UTC by TRdeXtremiana

Favicon de la nueva página

2022-11-23 15:49 UTC, alexpmAW approved these changes

2022-11-23 15:50 UTC, alexpmAW approved these changes

2022-11-23 15:52 UTC, DanielAlonsoDAW approved these changes

2022-11-23 15:55 UTC, alexpmAW requested changes
Resize the image to match favicon standard.

2022-11-23 16:01 UTC, alexpmAW requested changes
Resize the logo icon to a bigger size one.

2022-11-23 16:28 UTC, alexpmAW approved these changes

2022-11-23 16:30 UTC, Kuroval approved these changes
Me gusta, nos representan

2022-11-23 16:30 UTC, DanielAlonsoDAW approved these changes

2022-11-27 12:57 UTC, ftp-andrei approved these changes

2022-11-29 18:49 UTC, merged