4 Wireframe video
ftp-andrei/GrupoUnown pull request #19
Opened 2022-11-29 19:12 UTC by TRdeXtremiana

2022-11-30 08:18 UTC, DanielAlonsoDAW requested changes
En el Nav falta "Video"

2022-11-30 15:34 UTC, DanielAlonsoDAW approved these changes

2022-11-30 18:10 UTC, alexpmAW approved these changes

2022-12-01 15:56 UTC, ftp-andrei approved these changes
ok

2022-12-01 15:57 UTC, merged