Feature/14
ftp-andrei/GrupoUnown pull request #22
Opened 2022-11-30 16:07 UTC by ftp-andrei

Creacion guia estilos

2022-11-30 16:50 UTC, Kuroval requested changes
En el apartado Logo e Icono de grupo añade el icono

2022-11-30 17:49 UTC, DanielAlonsoDAW approved these changes

2022-11-30 22:26 UTC, Kuroval approved these changes

2022-11-30 22:30 UTC, TRdeXtremiana approved these changes

2022-12-01 16:01 UTC, alexpmAW approved these changes

2022-12-02 07:23 UTC, merged