Feature/11
ftp-andrei/GrupoUnown pull request #27
Opened 2022-12-03 14:12 UTC by ftp-andrei

Creado el html con etiquetas y demás. Lo único que no sabía muy bien que poner en la descripcion del video ya que no está creado, puse algo sin mas. 

Si se os ocurre algo decid.

2022-12-03 14:24 UTC, Kuroval requested changes
Esta también añadido el html de podcast y al vídeo yo le pondría controls nada mas porque no me gusta que los vídeos empiecen solos a reproducirse ni que empiecen de nuevo al acabar pero eso ya como queráis.

2022-12-03 15:16 UTC, Kuroval approved these changes

2022-12-03 17:56 UTC, DanielAlonsoDAW approved these changes

2022-12-04 13:02 UTC, alexpmAW approved these changes

2022-12-04 13:03 UTC, merged